version: '3.8'

services:
  mysql:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inRKI@0510
      MYSQL_USER: db
      MYSQL_PASSWORD: inRKI@0510
    expose:
      - '3306'
    ports:
      - "3309:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
    driver: local
