version: '3.8'

services:
  mysql:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inRKI@0510
      MYSQL_USER: root
      MYSQL_PASSWORD: inRKI@0510
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

